//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel.DomainServices.Hosting;
using System.ServiceModel.DomainServices.Server;
using Telerik.OpenAccess;

#pragma warning disable 1591

namespace CYMIMASA.OpenAccess	
{    
    [EnableClientAccess()]
    public partial class DomainService1 : OpenAccessDomainService</* Your context type */>
	{
		public DomainService1() : base()
		{
		}
	}
}

#pragma warning restore 1591
