//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYMIMASA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class IntranetEntities : DbContext
    {
        public IntranetEntities()
            : base("name=IntranetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MAccidActosInseguros> MAccidActosInseguros { get; set; }
        public DbSet<MAccidClasificacionAccidente> MAccidClasificacionAccidente { get; set; }
        public DbSet<MAccidCondicionesInseguras> MAccidCondicionesInseguras { get; set; }
        public DbSet<MAccidConsecuencias> MAccidConsecuencias { get; set; }
        public DbSet<TAccidentes> TAccidentes { get; set; }
        public DbSet<MAccidEvaluarRiesgo> MAccidEvaluarRiesgo { get; set; }
        public DbSet<MAccidFormaSuceso> MAccidFormaSuceso { get; set; }
        public DbSet<MAccidHora> MAccidHora { get; set; }
        public DbSet<MAccidLugarTrabajo> MAccidLugarTrabajo { get; set; }
        public DbSet<MAccidParteLesionada> MAccidParteLesionada { get; set; }
        public DbSet<MAccidTipoAccion> MAccidTipoAccion { get; set; }
        public DbSet<MAccidTipoGrafico> MAccidTipoGrafico { get; set; }
        public DbSet<MAccidTipoLesion> MAccidTipoLesion { get; set; }
        public DbSet<MAccidTipoRiesgo> MAccidTipoRiesgo { get; set; }
        public DbSet<MCentrosOperativos> MCentrosOperativos { get; set; }
        public DbSet<MDelegacion> MDelegacion { get; set; }
        public DbSet<MDivision> MDivision { get; set; }
        public DbSet<MEmpresas> MEmpresas { get; set; }
        public DbSet<MEtiquetas> MEtiquetas { get; set; }
        public DbSet<MPaises> MPaises { get; set; }
        public DbSet<MPersonal> MPersonal { get; set; }
        public DbSet<MSiNo> MSiNo { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<AccidentesGetXBO_Result> AccidentesGetXBO(string iDBO, string idioma)
        {
            var iDBOParameter = iDBO != null ?
                new ObjectParameter("IDBO", iDBO) :
                new ObjectParameter("IDBO", typeof(string));
    
            var idiomaParameter = idioma != null ?
                new ObjectParameter("Idioma", idioma) :
                new ObjectParameter("Idioma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccidentesGetXBO_Result>("AccidentesGetXBO", iDBOParameter, idiomaParameter);
        }
    }
}
