//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYMIMASA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEtiquetas
    {
        public string Seccion { get; set; }
        public string Nombre { get; set; }
        public string Etiqueta { get; set; }
        public string Idioma { get; set; }
    }
}
